version: "3.8"

services:
  auth:
    build:
      context: ./backend/auth
      args:
        SERVICE_NAME: auth
    ports:
      - "8081:8081"
    networks:
      - backend

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    environment:
      AUTH_URL: "http://auth:8081"
      STORAGE_URL: "http://storage:8002"
      ANALYSIS_URL: "http://analysis:8003"
      ENCRYPT_URL: "http://encrypt:8004"
    networks:
      - backend
    depends_on:
      - auth

  ui:
    build: ./frontend
    ports:
      - "5173:3000"
    networks:
      - backend
    depends_on:
      - gateway

networks:
  backend:
    driver: bridge
