version: "3.8"

services:
  auth:
    build:
      context: ./backend
      args:
        SERVICE_NAME: auth
    environment:
      PORT: 8001
    networks:
      - backend

  storage:
    build:
      context: ./backend
      args:
        SERVICE_NAME: storage
    environment:
      PORT: 8002
    networks:
      - backend

  analysis:
    build:
      context: ./backend
      args:
        SERVICE_NAME: analysis
    environment:
      PORT: 8003
    networks:
      - backend

  encrypt:
    build:
      context: ./backend
      args:
        SERVICE_NAME: encrypt
    environment:
      PORT: 8004
    networks:
      - backend

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    environment:
      AUTH_URL: "http://auth:8001"
      STORAGE_URL: "http://storage:8002"
      ANALYSIS_URL: "http://analysis:8003"
      ENCRYPT_URL: "http://encrypt:8004"
    networks:
      - backend
    depends_on:
      - auth
      - storage
      - analysis
      - encrypt

  ui:
    build: ./frontend
    ports:
      - "8501:8501"
    networks:
      - backend
    environment:
      GATEWAY_URL: "http://gateway:8000"
    depends_on:
      - gateway

networks:
  backend:
    driver: bridge
